### ISSUE TITLE
Add all base types & flesh out all base types with useful constraints

### ISSUE THREAD

**Issue by Olian04** [Olian04/Recordari#9]
- [x] R
  - [x] not: R
  - [x] or(R[]): Void
  - [x] and(R[]): Void
  - [x] Number: Number
  - [x] String: String
  - [x] Boolean: Boolean
  - [x] Array: Array
  - [x] Object: Object
  - [x] Regex: Regex
  - [x] Null: Void
  - [x] Undefined: Void
  - [x] Any: Void
  - [x] Custom(predicate): R
- [x] Number
  - [x] not: Number
  - [x] Natural: Number
  - [x] Whole: Number
  - [x] Max(num): Number
  - [x] Min(num): Number
  - [x] Exact(num): Number
  - [x] Mod(num, num): Number
  - [x] Either(num[]): Number
  - [x] Between(num_a, num_b): Number
- [x] String
  - [x] not: String
  - [x] Length: Number
  - [x] Exact(str): String
  - [x] Either(str[]): String
  - [x] StartsWith(str): String
  - [x] EndsWith(str): String
  - [x] Matches(regex): String
- [x] Boolean
  - [x] True: Void
  - [x] False: Void
- [x] Array
  - [x] Length: Number
  - [x] Contains: R
  - [x] Each: R
  - [x] Like(array): Void
- [x] Object
  - [x] Values: Array
  - [x] Keys: Array
  - [x] Like(obj): Void
- [x] Regex
  - [x] Test(str): Boolean
- [x] Void
